#!/bin/bash
# set -x
set -e

if [ ! -e /tmp/$0-messages ]; then
curl -s -G 'https://recurse.zulipchat.com/api/v1/messages' \
    -u cdosborn@email.arizona.edu:typKXxzqYik20zhdHSmFY85xH7wbTmnw \
    --data-urlencode 'narrow=[{"operator":"stream", "operand":"blogging"}]' \
    --data-urlencode 'num_before=35000' \
    --data-urlencode 'num_after=35000' \
    --data-urlencode 'use_first_unread_anchor=true' \
    --data-urlencode client_gravatar=false \
    --data-urlencode apply_markdown=false | \
    jq -r '.messages[] | [.sender_id, .timestamp, .subject] | map(tostring) | join(" ")' > /tmp/$0-messages
fi

python < /tmp/$0-messages <(
cat <<PY
import sys
topics = {}
for line in sys.stdin.read().splitlines():
    (sender_id, timestamp, topic) = line.split(" ", 2)
    topics[topic] = topics.get(topic, { "sender_set": set(), "timestamp": None })
    if sender_id == "100053" or sender_id == "1921":
        topics[topic]["timestamp"] = timestamp
    else:
        topics[topic]["sender_set"].add(sender_id)
for topic in topics.keys():
    num_unique_senders = len(topics[topic]["sender_set"])
    print num_unique_senders
PY
) | \

awk '{ S=int($1/BUCKET);

        if((MIN=="")||(S<MIN)) MIN=S
        if((MAX=="")||(S>MAX)) MAX=S;
        A[S]++;
        T++ }

END {
        for(N=MIN; N<=MAX; N++)
                printf("%f %d\n", A[N]/T, N*BUCKET);
}' BUCKET=1
